#!/bin/bash


#Skript, mis arvutab sisestatud arvude summa ja valjastab selle selgitava tegstiga

read -p "Sisesta suvaline taisarv:" arv


summa=0
while [ $arv -ne 0 ]
do
	jaak=$(($arv % 10))
	summa=$(($summa + $jaak))
	arv=$(($arv / 10))
done
echo "Sinu arvu numbrite summa on : $summa"
