#!/bin/bash

#Skript, mis tervitab kasutajat

aeg=$(date +"%H")
kasutaja=$(whoami)


if [ $aeg -ge 6 -a $aeg -lt 12 ]; then
	tervitus="Tere hommikust!"
elif [ $aeg -ge 12 -a $aeg -lt 18 ]; then
	tervitus="Tere paevast!"
elif [ $aeg -ge 18 -a $aeg -lt 22 ]; then
	tervitus="Tere ohtust!"
elif [ $aeg -ge 22 -a $aeg -lt 24 ] || [ $aeg -ge 0 -a $aeg -lt 6 ]; then
	tervitus="Head ood!"
fi
echo "$tervitus, $kasutaja !"


